### ISSUE TITLE
svyzengacurve sometimes gives all missings on svrepdesign object

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#137]
library(convey)
	library(survey)

	n <- 10

	dist_frame <-
		data.frame( 
			wt_binom = rbinom( n , 1 , .5 ) ,
			pois1 = rpois( n , 1 ) 
		)

	binom_des <- convey_prep( svydesign( ~ 1 , data = dist_frame , weight = ~ wt_binom ) )
	binom_rep <- convey_prep( as.svrepdesign( binom_des , type = 'bootstrap' ) )

	# seems correct..
	svyzengacurve( ~ pois1 , binom_des )

	# ..all missings
	svyzengacurve( ~ pois1 , binom_rep )

**Comment by guilhermejacob** [comment]
I removed a block from svyzengacurve and svylorenz that was responsible for this. That block checked there was any NA in the replicates. If so, it returned NAs.
The problem here is the following: the weight vector of some replicates are composed only by 0s, therefore no population existed. If you add a + 1 to your original weights it works, since there is no combination with only 0s.
Anyways, now it works (:
