### ISSUE TITLE
add remaining functions to test-skewed_distributions.R

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#218]
https://github.com/DjalmaPessoa/convey/blob/master/tests/testthat/test-skewed_distributions.R

just took out `svybmi` because it's failing, but all of the other new functions like `svysst` and `svysen` should be incorporated into this loop.  (there are plenty of exceptions written near the bottom.)  thanks

**Comment by guilhermejacob** [comment]
commit 4854311acdd0efadc2f10e3766e68918bda6cf1f added tests for svysen, svysst, svybmi and svybcc.
That's it, right?

**Comment by ajdamico** [comment]
thanks, it should include all of the main `svy*` functions in https://github.com/DjalmaPessoa/convey/tree/master/R but not sure whether you want to include the decomposition functions as well..  your decision

**Comment by guilhermejacob** [comment]
I'm not sure, but I don't think so. If it works for the general case, it works for the decomposition, since they should match.

**Comment by guilhermejacob** [comment]
I thought about this for a while. The real problem here is that we would have to simulate (at least) two distributions in order to provide meaningful results for the group decomposition. 
I don't think it is worth it, though. If there was something wrong with the decomposition, the decomposed values wouldn't add up to the non-decomposed index.

Maybe this would be better: test whether the decomposed values add up to the non-decomposed index.
What do you think, @ajdamico ?

**Comment by ajdamico** [comment]
great

**Comment by ajdamico** [comment]
i think it looks great..thank you
