### ISSUE TITLE
please clarify the utility of `empirical=TRUE` in the docs?

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#57]
it doesn't appear to make any difference, except the line is a little thicker.  reproducible example below, thanks!

	# get latest version
	# devtools::install_github("djalmapessoa/convey")

	library(convey)
	library(survey)
	library(vardpoor)
	data(eusilc) ; names( eusilc ) <- tolower( names( eusilc ) )
	library(convey)

	# linearized design
	des_eusilc <- svydesign( ids = ~rb030 , strata = ~db040 ,  weights = ~rb050 , data = eusilc )
	des_eusilc <- convey_prep( des_eusilc )

	# the line appears thin because of `svylorenzpolygon_wrap`
	svylorenz( ~eqincome , design = des_eusilc, quantiles = seq(0,1,.05), alpha = .01 )
	# the line appears thicker because of `svylorenzlines_wrap`
	svylorenz( ~eqincome , design = des_eusilc, quantiles = seq(0,1,.05), alpha = .01 , empirical = TRUE )

	# replicate-weighted design
	des_eusilc_rep <- survey:::as.svrepdesign( des_eusilc , type = "bootstrap" )
	des_eusilc_rep <- convey_prep( des_eusilc_rep )
	# the line appears thin because of `svylorenzpolygon_wrap`
	svylorenz( ~eqincome , design = des_eusilc_rep, quantiles = seq(0,1,.05), alpha = .01 )
	# the line appears thicker because of `svylorenzlines_wrap`
	svylorenz( ~eqincome , design = des_eusilc_rep, quantiles = seq(0,1,.05), alpha = .01 , empirical = TRUE)

**Comment by guilhermejacob** [comment]
The empirical option adds an observation-based Lorenz Curve, whilst the typical curve is defined on the proper quantiles. As the number of quantiles increase, the typical curve gets closer to the empirical.
For being observation-based, there (probably) isn't an observation with quantile = .10 on the empirical curve, so the one below and the one above .10 has to be interpolated to reach this precise number.
The empirical version is the one actually used to estimate the Gini index, since the other one would underestimate the area between the equality line and the curve. But the quantile-based one is used to estimate the share sum, its SE and confidence interval.
For instance, try running this:
```
svylorenz( ~eqincome , design = des_eusilc_rep, quantiles = seq(0,1,.2), alpha = .01 )
svylorenz( ~eqincome , design = des_eusilc_rep, quantiles = seq(0,1,.2), alpha = .01, curve.col = "green", ci = F, empirical = T, add = T )
```
You will notice that the red shades and the green line are slightly different this time. Also, notice that I chose not to estimate the CI for the second one, as they would be exactly the same.
Did this help?

**Comment by ajdamico** [comment]
thanks!  could you:

(1) pick an example where the difference is more extreme?  these two lines
look very close to one another.  you might be better off with
quantiles=c(0,0.5,1)  ?

(2) add the explanation to the documentation, not just here in this
discussion?  that way, users will be able to read about its usage when they
type  ?svylorenz

thanks!!

**Comment by guilhermejacob** [comment]
Done.
