### ISSUE TITLE
now that `convey_prep` stores the full design, is it possible to remove more parameters?

### ISSUE THREAD

**Issue by ajdamico** [DjalmaPessoa/convey#9]
some examples-

https://github.com/DjalmaPessoa/convey/blob/master/R/svyarpr.R#L54

https://github.com/DjalmaPessoa/convey/blob/master/R/svygpg.R#L66

https://github.com/DjalmaPessoa/convey/blob/master/R/svyrmpg.R#L57-L58

**Comment by DjalmaPessoa** [comment]
Sorry to disturb you, but I need a suggestion.

Now with the use of convey_prep I can recover the full_design inside a
function.
I'm going to use this to simplify arguments.
But also I have the situation where I need to use full_design as argument
of a function inside other. For example,
inside svyarpr_new there is:

ARPT <- svyarpt_new(formula=formula, design = full_design, order = order,
    percent = percent, comp=TRUE, attr_des = FALSE )

I got an error because full_design has no attributes.

Any simple suggestion?

**Comment by ajdamico** [comment]
add a parameter to each of your main functions `definitely_is_full_design = FALSE`

then change the lines 

    full_design <- attr( design , "full_design" )

to

     if( definitely_is_full_design ) full_design <- design else full_design <- attr( design , "full_design" )

and when you call your main functions from within other functions and you already know that the design you are passing is the full one, you can set this to TRUE and you will not encounter this problem.  in general, the user can always leave this as FALSE.

**Comment by ajdamico** [comment]
i believe this technique solves the problem?

https://github.com/DjalmaPessoa/convey/commit/c9635250de16141840947718cead03298d92bfe9

**Comment by DjalmaPessoa** [comment]
I just made a commit with some of the new functions and the fixed the
examples.

Please try to run the example of svyarpr. I got an error message:

Error: $ operator is invalid for atomic vectors
In addition: Warning message:
In if (class(attr(design, "full_design")) == "logical") full_design <-
design else full_design <- attr(design,  :
  the condition has length > 1 and only the first element will be used.

**Comment by DjalmaPessoa** [comment]
All  functions had the arguments removed. The argument "comp" could be removed from some functions. This possibility has to considered.
